# Config file for: https://pre-commit.com/
# These are run prior to every commit made in this repository
repos:
  # Nice basic pre-commit hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: check-byte-order-marker
      - id: check-executables-have-shebangs
      - id: debug-statements
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: detect-private-key
      - id: check-symlinks
      - id: name-tests-test
        args: ["--django"]
      - id: check-added-large-files
        args: ["--maxkb=700"]
  # Prettier
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "" # Use the sha or tag you want to point at
    hooks:
      - id: prettier
        name: Prettier for formatting
  # Lint of terraform with tflint
  - repo: https://github.com/antonbabenko/pre-commit-terraform.git
    rev: "v1.48.0"
    hooks:
      - id: terraform_tflint
      - id: terraform_docs
      - id: terraform_fmt
  # Docker chekcs + docker hadolint
  - repo: https://github.com/IamTheFij/docker-pre-commit
    rev: v2.0.0
    hooks:
      - id: docker-compose-check
      - id: hadolint-system
  # Python security linters
  - repo: https://github.com/PyCQA/bandit
    rev: 1.6.2
    hooks:
      - id: bandit
        args: ["-iii", "-ll"]
  # Safety python package checker
  - repo: https://github.com/Lucas-C/pre-commit-hooks-safety
    rev: v1.2.1
    hooks:
      - id: python-safety-dependencies-check
  # Skjold python security scanner
  - repo: https://github.com/twu/skjold
    rev: v0.2.1
    hooks:
      - id: skjold
  # Custom hooks
  - repo: local
    hooks:
      # PyLint, PEP8 & McCube complexity
      - id: prospector
        name: Prospector (pylint, pyflakes, bandit, mypy, mccabe)
        entry: prospector --messages-only --profile-path prospector.yaml
        language: python
        types: [python]
        # Settings, migrations, apps.py and __init__ files are special
        # files which are not easily auto-checked, and which do not contain logic
        exclude: (.+/(core_settings|migrations)/.+|.+/(apps.py|__init__.py))
        pass_filenames: true
