apiVersion: machinelearning.seldon.io/v1alpha2
kind: SeldonDeployment
metadata:
  name: mlflow-wine
  namespace: seldon
spec:
  name: wines
  predictors:
    - graph:
        children: []
        implementation: MLFLOW_SERVER
        modelUri: gs://seldon-models/mlflow/elasticnet_wine
        name: classifier
      name: default
      replicas: 1
      componentSpecs:
        - spec:
            containers:
              - name: classifier
                livenessProbe:
                  initialDelaySeconds: 80
                  failureThreshold: 200
                  periodSeconds: 5
                  successThreshold: 1
                  httpGet:
                    path: /health/ping
                    port: http
                    scheme: HTTP
                readinessProbe:
                  initialDelaySeconds: 80
                  failureThreshold: 200
                  periodSeconds: 5
                  successThreshold: 1
                  httpGet:
                    path: /health/ping
                    port: http
                    scheme: HTTP
